### ISSUE TITLE
Improvements to ORT run results pages

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#914]
Features not implemented yet by closing of #680 or pending:
- [ ] logs of the run: streaming -> pending on further implementation, possibly a bigger issue to discuss
- [x] issues list, depends on #405 
- [x] vulnerability list, #988
- [x] rule violation list, depends on #795 

Ideas from the frontend alignment meeting 27.8.2024:

- [ ] show badge next to menu items, e.g., for vulnerabilities, show the number of vulnerabilities (and maybe by severity, with different badge colors) -> statistics cards used instead
- [x] move issues to separate page, #959
- [x] move job details to separate page (in technical section of the sidebar), #917 
- [x] traffic lights in run index page could link to technical section with the right job selected, #643, #917
- [x] show only summaries in overview page, like number of issues by severity
- [ ] show some statistical data in the overview page, e.g. a pie chart with number of projects per package manager -> pending on further discussion
- [x] show item next to menu items where data is still being generated, e.g. a spinner if the evaluator job is still running, or another item if it did not even start yet
- [x] maybe show traffic lights in overview page, because users know it from the ort runs list, #936

**Comment by Etsija** [comment]
As the items left in this to-do list are either implemented in a different way, or pending on discussion / further implementation, I will close this for now, as it's served its purpose.
